version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/sysadmin/config/defaultFront.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
    command: serve -s build
