version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/sysadmin/config/defaultFront.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
    command: serve -s build
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  reverseproxy:
    image: nginx:alpine
    volumes:
      - /home/sysadmin/config/default.conf:/etc/nginx/conf.d/default.conf
      - /home/sysadmin/config/nginx.conf:/etc/nginx/nginx.conf
      - /home/sysadmin/ssl/privkey.pem:/ssl/privkey.pem
      - /home/sysadmin/ssl/fullchain.pem:/ssl/fullchain.pem
      - /home/sysadmin/ssl/dhparam-2048.pem:/ssl/dhparam-2048.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
    #depends_on:
    #  - backend
    #  - frontend
    #  - meeting

networks:
  mynetwork:
    external: true
