name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Create SSH key file
      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Start SSH agent and add private key
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan -H cp24ssa2.sit.kmutt.ac.th >> ~/.ssh/known_hosts

      # Step 3: Deploy Frontend Container and Start It via SSH
      - name: Deploy Container and Start It
        run: |
          ssh -o StrictHostKeyChecking=no sysadmin@cp24ssa2.sit.kmutt.ac.th << 'EOF'
            cd /home/sysadmin/MedVista && \
            git pull && \
            npm install -g serve && \
            npm run build && \
            docker-compose up -d --build frontend
          EOF
